"""ok

Revision ID: 5c1da76b9b46
Revises: 2775b5039342
Create Date: 2021-10-30 09:41:51.478033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1da76b9b46'
down_revision = '2775b5039342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_event', sa.Column('do', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_event', 'do')
    # ### end Alembic commands ###
