"""ok

Revision ID: 83ff338af4c9
Revises: 5c1da76b9b46
Create Date: 2021-11-01 05:53:36.905019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ff338af4c9'
down_revision = '5c1da76b9b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'title')
    # ### end Alembic commands ###
